### ISSUE TITLE
Bounced contact: b8b4ddba-06d4-44ad-ad66-ef9274a496ea

### ISSUE THREAD

**Issue by kevinlove** [iDigBio/idb-us-collections#1449]
https://github.com/iDigBio/idb-us-collections/blob/master/collections/b8b4ddba-06d4-44ad-ad66-ef9274a496ea

Looks like the Black Belt Museum is having hosting issues:

http://www.blackbeltmuseum.com/

We may need to get someone on the phone to see if they are aware of the issue.

**Comment by ShariEllis** [comment]
The museum is currently active on Facebook. It is based at the U of W. Alabama and the links on the university website lead to a page that says the account is suspended.
