### ISSUE TITLE
CUMV Reptile Collection (Arctos) - ADD request

### ISSUE THREAD

**Issue by JoannaMcCaffrey** [iDigBio/idb-us-collections#420]
```json
{
    "institution": "Cornell University, Museum of Vertebrates",
    "collection": "Reptiles",
    "recordsets": "7d47b53b-0a12-40e6-b57c-676021a2b18f",
    "institution_code": "CUMV",
    "collection_code": "Reptile specimens",
    "collection_uuid": "",
    "collection_lsid": "http://grbio.org/cool/vg5r-57jw",
    "collection_url": "http://www.cumv.cornell.edu/",
    "collection_catalog_url": "http://arctos.database.museum/cumv_rept",
    "contact": "John Friel",
    "contact_role": "Curator",
    "contact_email": "john.friel@cornell.edu",
    "taxonomic_coverage": "",
    "geographic_range": "",
    "collection_size": "NA",
    "mailing_address": "159 Sapsucker Woods Road",
    "mailing_city": "Ithaca",
    "mailing_state": "New York",
    "mailing_zip": "14850-1923",
    "physical_address": "159 Sapsucker Woods Road",
    "physical_city": "Ithaca",
    "physical_state": "New York",
    "physical_zip": "14850-1923",
    "update_url": "",
    "lat": 42.4793,
    "lon": -76.4505
}
```

**Comment by kevinlove** [comment]
The collection has a UUID, is it new?

**Comment by JoannaMcCaffrey** [comment]
@kevinlove Yes, not sure of your question, it is a new collection to the list, and we have their data.

**Comment by kevinlove** [comment]
How does a new collection have a collection UUID created by us?

The question is, since this collection already exists (https://www.idigbio.org/portal/collections/6f55b5bd-7a59-4aad-9b31-c71344d25e67), how would you like me to proceed with this request to create a new collection?

**Comment by JoannaMcCaffrey** [comment]
@kevinlove I wrote the new collection record with a UUID; I realized we did not have a collection record in the list when I went to process it after we had ingested the dataset. We can close this.

**Comment by kevinlove** [comment]
I'm going to close this ticket, but I want to be clear:

You shouldn't be assigning "collection_uuid", these are minted when I create stub records. A request for a new collection should ALWAYS come in with this field blank.

**Comment by kevinlove** [comment]
On further thought, we need to have a discussion about this. It looks like you were trying to create a collection called "Reptiles", but had a copy paste error and provided the collection "Amphibians" collection_uuid.

Can you give me a call to discuss.

**Comment by JoannaMcCaffrey** [comment]
@kevinlove There are two collections:
Reptiles: https://www.idigbio.org/portal/recordsets/7d47b53b-0a12-40e6-b57c-676021a2b18f
Amphibians: https://www.idigbio.org/portal/recordsets/80daac2f-e496-4c65-b196-6be7a9c4c98e

I goofed with the "collection_uuid": "urn:uuid:6f55b5bd-7a59-4aad-9b31-c71344d25e67"

**Comment by kevinlove** [comment]
I'll go ahead and process this new request, for future reference, you can always edit the submission to correct the error.
