### ISSUE TITLE
Any New Collections to Add or Updates?

### ISSUE THREAD

**Issue by kevinlove** [iDigBio/idb-us-collections#602]
@JoannaMcCaffrey  As we discussed in our last meeting, I'd like to begin to make some changes to the schema. I don't really want to begin that work until we can freeze our current queue of updates though. Can you please use this ticket to indicate when you have all of your outstanding updates processed or when your are ready to freeze changes.

Thanks!

**Comment by JoannaMcCaffrey** [comment]
@kevinlove I'll be done by the end of the day, and even if not, I can cease until you say the DB is open again.

**Comment by kevinlove** [comment]
Ok, continue to make updates. We will freeze updates from 1/6-1/9.

**Comment by kevinlove** [comment]
@JoannaMcCaffrey  Forgot to mention, once you've made your last update today, please close this ticket to indicate that we are ready to freeze.

**Comment by JoannaMcCaffrey** [comment]
@kevinlove All done - no more until you tell me it is open again and there are more datasets ingested!
